
thorchain:
  chain_rpc: "http://your-forked-thorchain-ip:26657"  # RPC endpoint of forked THORChain
  chain_host: "http://your-forked-thorchain-ip:1317"  # REST API endpoint
  chain_id: "thorchain-testnet"  # Match your forked chain ID
  
chains:
  bitcoin:
    disabled: false
    rpc_host: "http://bitcoind-regtest:18443"
    rpc_user: "thorchain"
    rpc_pass: "password"
    block_scanner:
      start_block_height: 1
      block_scan_processors: 1
    
  ethereum:
    disabled: false
    rpc_host: "http://anvil-eth:8545"
    cosmos_grpc_host: "your-forked-thorchain-ip:9090"
    block_scanner:
      start_block_height: 1
      block_scan_processors: 1
    router_contract_address: "0x..." # Deploy Router.sol on your anvil fork
    
  binance:
    disabled: true  # Enable if testing BSC
    rpc_host: "http://bsc-testnet:8545"
    
  litecoin:
    disabled: true
  bitcoin_cash:
    disabled: true
  dogecoin:
    disabled: true
  avalanche:
    disabled: true

tss:
  bootstrap_peers: []  # Will be populated by THORChain
  external_ip: ""      # Auto-detect or set manually
  
metrics:
  enabled: true
  listen_port: 9000
