# Docker Compose for Bifrost + External Chain Testing
# Complements the THORChain package deployment

version: '3.8'

services:
  # Bifrost daemon pointing to forked THORChain
  bifrost:
    image: "registry.gitlab.com/thorchain/thornode:mainnet"
    command: ["bifrost", "-c", "/etc/bifrost/config.yaml"]
    ports:
      - "9000:9000"  # Metrics
      - "6040:6040"  # P2P
    volumes:
      - ./bifrost-config-stub.yaml:/etc/bifrost/config.yaml:ro
      - bifrost_data:/root/.thornode
    environment:
      - THORCHAIN_RPC=http://your-forked-thorchain-ip:26657
      - THORCHAIN_API=http://your-forked-thorchain-ip:1317
    depends_on:
      - bitcoind-regtest
      - anvil-eth
    restart: unless-stopped

  # Bitcoin regtest for testing
  bitcoind-regtest:
    image: "ruimarinho/bitcoin-core:latest"
    command: [
      "bitcoind",
      "-regtest",
      "-server",
      "-rpcallowip=0.0.0.0/0",
      "-rpcuser=thorchain",
      "-rpcpassword=password",
      "-rpcport=18443",
      "-port=18444",
      "-fallbackfee=0.0001"
    ]
    ports:
      - "18443:18443"  # RPC
      - "18444:18444"  # P2P
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    restart: unless-stopped

  # Ethereum anvil fork
  anvil-eth:
    image: "ghcr.io/foundry-rs/foundry:latest"
    command: [
      "anvil",
      "--host", "0.0.0.0",
      "--port", "8545",
      "--fork-url", "https://eth-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY",
      "--fork-block-number", "18000000"  # Adjust as needed
    ]
    ports:
      - "8545:8545"
    restart: unless-stopped

  # Router contract deployment helper
  router-deployer:
    image: "ghcr.io/foundry-rs/foundry:latest"
    command: ["sleep", "infinity"]  # Keep alive for manual deployment
    volumes:
      - ./router-contracts:/contracts:ro
    environment:
      - ETH_RPC_URL=http://anvil-eth:8545
    depends_on:
      - anvil-eth
    profiles:
      - tools

volumes:
  bifrost_data:
  bitcoin_data:

networks:
  default:
    name: thorchain-testing
