
chains:
  - name: thorchain-contract-test
    type: thorchain
    chain_id: "thorchain-testnet"
    
    forking:
      enabled: true
      rpc: "https://rpc.ninerealms.com"
      chain_id: "thorchain-mainnet-v1"
      height: 22071722  # Adjust to recent height
      cache_enabled: true
      cache_size: 10000
      timeout: "60s"
      gas_cost_per_fetch: 1000
    
    participants:
      - image: "tiljordan/thornode-forking:1.0.13"
        account_balance: 1000000000000000
        bond_amount: "300000000000000"
        count: 1
        min_cpu: 1000  # Higher resources for contract testing
        min_memory: 1024
    
    additional_services: ["faucet", "bdjuno", "swap-ui"]
    
    prefunded_accounts:
      "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about": "10000000000000"
      "thor1contract1test1account1address1here1234567890": "5000000000000"
      "thor1contract2test2account2address2here1234567890": "5000000000000"
    
    chain_contracts: []  # Will be populated after deployment
    
    modules:
      wasm:
        code_upload_access:
          permission: "Everybody"  # Ensure open permissions
          addresses: []
        instantiate_default_permission: "Everybody"

bifrost_config:
  enabled: true
  config_file: "./bifrost-config-stub.yaml"
  external_chains:
    bitcoin:
      enabled: true
      type: "regtest"
    ethereum:
      enabled: true
      type: "anvil_fork"
      router_deploy: true
    
test_scenarios:
  contract_deployment:
    - name: "basic_upload"
      description: "Test basic contract upload and instantiation"
      contracts: ["counter", "cw20_token"]
    - name: "permission_verification" 
      description: "Verify WASM permissions match between network types"
      compare_networks: ["local", "forked"]
    - name: "state_persistence"
      description: "Test contract state persistence across restarts"
      
  bifrost_integration:
    - name: "connection_test"
      description: "Test bifrost connection to forked THORChain"
    - name: "cross_chain_monitoring"
      description: "Verify cross-chain transaction monitoring"
    - name: "external_chain_interaction"
      description: "Test interaction with forked external chains"
